include $(THEOS)/makefiles/common.mk

TOOL_NAME = tweaksettings-utility

tweaksettings-utility_FILES = main.c
tweaksettings-utility_CFLAGS = -Wall -Wextra -Werror
tweaksettings-utility_CODESIGN_FLAGS = -Sentitlements.plist

include $(THEOS_MAKE_PATH)/tool.mk
